
version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: 974073908437.dkr.ecr.us-east-1.amazonaws.com/my-repo

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "ECR_REPOSITORY_URI=$ECR_REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build --no-cache --pull -t ${ECR_REPOSITORY_URI}:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push ${ECR_REPOSITORY_URI}:latest
      - echo "[{\"name\":\"nani\",\"imageUri\":\"${ECR_REPOSITORY_URI}:latest\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - '/root/.nuget/**/*'
