version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    # Changed from 8080:80 to 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
